create table client_entity (id integer generated by default as identity, balance bigint not null, limite bigint not null, primary key (id));
create table transaction_entity (client_id integer, id integer generated by default as identity, type tinyint check (type between 0 and 1), amount bigint not null, created_at timestamp(6) with time zone, description varchar(255), primary key (id));
alter table if exists transaction_entity add constraint FKoykvsm64e0mpn8jslx3jsi5bt foreign key (client_id) references client_entity;
create table client_entity (id integer generated by default as identity, balance bigint not null, limite bigint not null, primary key (id));
create table transaction_entity (client_id integer, id integer generated by default as identity, type tinyint check (type between 0 and 1), amount bigint not null, created_at timestamp(6) with time zone, description varchar(255), primary key (id));
alter table if exists transaction_entity add constraint FKoykvsm64e0mpn8jslx3jsi5bt foreign key (client_id) references client_entity;
