create table client_entity (
    id integer generated by default as identity,
    balance bigint not null,
    limite bigint not null, 
    primary key (id)
);

create table transaction_entity (
    client_id integer,
    id integer generated by default as identity,
    type smallint check (type between 0 and 1),
    amount bigint not null,
    created_at timestamp(6) with time zone,
    description varchar(10),
    primary key (id)
);

create index idx_client_id ON transaction_entity (client_id);

alter table if exists transaction_entity 
    add constraint FKoykvsm64e0mpn8jslx3jsi5bt foreign key (client_id) references client_entity;

insert into client_entity values (1, 0, 100000);
insert into client_entity values (2, 0, 80000);
insert into client_entity values (3, 0, 1000000);
insert into client_entity values (4, 0, 10000000);
insert into client_entity values (5, 0, 500000);
